app:
  name: content-storage

image:
  repository: ghcr.io/darmoise/content-storage
  tag: latest
  pullPolicy: Always

service:
  port: 8080
  targetPort: 8080

container:
  port: 8080

env:
  SERVER_PORT: "8080"

ingress:
  enabled: true
  className: nginx
  host: stage.darmoise.github.io
  path: /storage
  pathType: Prefix
