apiVersion: v1
kind: Secret
metadata:
  name: account-api-secret
  namespace: easychat-stage
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "CHANGE_ME_STAGE"
  SPRING_MAIL_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME"
  TX_PROCESSOR_SECRET_KEY: "CHANGE_ME"
  ENCRYPTION_KEY: "CHANGE_ME"
  RPC_HELIUS_API_KEY: "CHANGE_ME"
  RPC_ALCHEMY_API_KEY: "CHANGE_ME"
